title:             Bdubz Site
email:             branwitz@gmail.com
description:       Sample of KIT
author:            Start Bootstrap
baseurl:           ""
url:               "https://branwitz.github.io/"

# Social Profiles
github_username:   branwitz


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
